apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    purpose: annotations-demo
    porject: roboshop
  annotations:
    description: "This is to know about how annotations works or used"
    jenkins: "https://jenkins.com/build/job/roboshop-catalogue"  #url's can be provided in annotations
spec:
  container:
  - name: nginx
    image: nginx