apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret-env
  labels: 
    purpose: secret-ref
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret