apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
  selector:
    project: roboshop
    environment: dev
    purpose: demo
  ports:
    - protocol: TCP
      port: 80        #serviceport
      targetPort: 80  #containerport
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    purpose: demo
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx