apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    purpose: Nodeport-demo
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev
    purpose: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-np
  labels:
    project: roboshop
    environment: dev
    purpose: demo
spec:
  containers:
  - name: nginx
    image: nginx
